#!/usr/bin/env bash
set -e

cargo watch -w src -w examples \
            -x "test --lib" \
            -x "test --doc" \
            -x clippy \
            -x "fmt -- --write-mode=diff" \
            -x "readme -o README.md"
